#ifndef _UAPI_NAMRBD_NETLINK_H_
#define _UAPI_NAMRBD_NETLINK_H_

/*
 * NAMRBD generic netlink interface for control-path commands.
 * Userland tool sends REST server configuration and attach/detach commands.
 * Kernel module performs REST calls directly.
 */

#define NAMRBD_GENL_FAMILY_NAME "NAMRBD_CTRL"
#define NAMRBD_GENL_VERSION 0x1

enum namrbd_cmd {
	NAMRBD_CMD_UNSPEC = 0,
	NAMRBD_CMD_CREATE_DEVICE = 1,
	NAMRBD_CMD_DESTROY_DEVICE = 2,
	NAMRBD_CMD_CONFIG_REST = 3,
	NAMRBD_CMD_ATTACH = 4,
	NAMRBD_CMD_DETACH = 5,
	NAMRBD_CMD_GET_STATUS = 6,
	NAMRBD_CMD_LIST_DEVICES = 7,
	NAMRBD_CMD_ATTACH_MANIFEST = 8,
	NAMRBD_CMD_DETACH_LOCAL = 9,
	NAMRBD_CMD_UPDATE_PATH_PLAN = 10,
	NAMRBD_CMD_RECONFIGURE_DATA_PATHS = 11,
	NAMRBD_CMD_RESIZE_DEVICE = 12,
	__NAMRBD_CMD_MAX,
};
#define NAMRBD_CMD_MAX (__NAMRBD_CMD_MAX - 1)

enum namrbd_attr {
	NAMRBD_ATTR_UNSPEC = 0,
	NAMRBD_ATTR_DEVICE_ID = 1,    /* u32 */
	NAMRBD_ATTR_DISK_NAME = 2,    /* NUL-terminated string */
	NAMRBD_ATTR_SERVERS = 3,      /* nested list of NAMRBD_ATTR_SERVER_ENTRY */
	NAMRBD_ATTR_SERVER_ENTRY = 4, /* nested server attrs */
	NAMRBD_ATTR_ATTACH_REQ = 5,   /* nested req attrs */
	NAMRBD_ATTR_DETACH_REQ = 6,   /* nested req attrs */
	NAMRBD_ATTR_DEVICE_STATUS = 7,/* nested status attrs */
	NAMRBD_ATTR_DEVICE_LIST = 8,  /* nested list of NAMRBD_ATTR_DEVICE_STATUS */
	NAMRBD_ATTR_STATUS = 9,       /* u32 */
	NAMRBD_ATTR_ERR_MSG = 10,     /* NUL-terminated string */
	NAMRBD_ATTR_MANIFEST_JSON = 11, /* NUL-terminated string */
	NAMRBD_ATTR_DOWN_MASK = 12,   /* u64 */
	NAMRBD_ATTR_DEGRADED_MASK = 13, /* u64 */
	NAMRBD_ATTR_DRAINING_MASK = 14, /* u64 */
	NAMRBD_ATTR_PATH_PLAN_REVISION = 15, /* u64 */
	NAMRBD_ATTR_SIZE_BYTES = 16, /* u64 */
	NAMRBD_ATTR_VOLUME_ID = 17, /* u64 */
	NAMRBD_ATTR_GENERATION = 18, /* u64 */
	__NAMRBD_ATTR_MAX,
};
#define NAMRBD_ATTR_MAX (__NAMRBD_ATTR_MAX - 1)

enum namrbd_server_attr {
	NAMRBD_SERVER_ATTR_UNSPEC = 0,
	NAMRBD_SERVER_ATTR_ID = 1,           /* u32 */
	NAMRBD_SERVER_ATTR_ADDRESS = 2,      /* NUL-terminated string */
	NAMRBD_SERVER_ATTR_PORT = 3,         /* u16 */
	NAMRBD_SERVER_ATTR_USE_TLS = 4,      /* u8 */
	NAMRBD_SERVER_ATTR_API_PREFIX = 5,   /* NUL-terminated string */
	NAMRBD_SERVER_ATTR_BEARER_TOKEN = 6, /* NUL-terminated string */
	__NAMRBD_SERVER_ATTR_MAX,
};
#define NAMRBD_SERVER_ATTR_MAX (__NAMRBD_SERVER_ATTR_MAX - 1)

enum namrbd_req_attr {
	NAMRBD_REQ_ATTR_UNSPEC = 0,
	NAMRBD_REQ_ATTR_DEVICE_ID = 1, /* u32 */
	NAMRBD_REQ_ATTR_HOST_ID = 2,   /* NUL-terminated string */
	NAMRBD_REQ_ATTR_VOLUME_ID = 3, /* u64 */
	__NAMRBD_REQ_ATTR_MAX,
};
#define NAMRBD_REQ_ATTR_MAX (__NAMRBD_REQ_ATTR_MAX - 1)

enum namrbd_status_attr {
	NAMRBD_STATUS_ATTR_UNSPEC = 0,
	NAMRBD_STATUS_ATTR_DEVICE_ID = 1,  /* u32 */
	NAMRBD_STATUS_ATTR_DISK_NAME = 2,  /* NUL-terminated string */
	NAMRBD_STATUS_ATTR_ATTACHED = 3,   /* u8 */
	NAMRBD_STATUS_ATTR_VOLUME_ID = 4,  /* u64 */
	NAMRBD_STATUS_ATTR_GENERATION = 5, /* u64 */
	NAMRBD_STATUS_ATTR_PATH_COUNT = 6, /* u32 */
	NAMRBD_STATUS_ATTR_DOWN_MASK = 7,  /* u64 */
	NAMRBD_STATUS_ATTR_DEGRADED_MASK = 8, /* u64 */
	NAMRBD_STATUS_ATTR_DRAINING_MASK = 9, /* u64 */
	NAMRBD_STATUS_ATTR_APPLIED_PATH_PLAN_REVISION = 10, /* u64 */
	NAMRBD_STATUS_ATTR_ACTIVE_LANE_COUNT = 11, /* u32 */
	NAMRBD_STATUS_ATTR_NR_HW_QUEUES = 12, /* u32 */
	NAMRBD_STATUS_ATTR_TARGET_NR_HW_QUEUES = 13, /* u32 */
	NAMRBD_STATUS_ATTR_QUEUE_TOPOLOGY_GENERATION = 14, /* u64 */
	NAMRBD_STATUS_ATTR_QUEUE_TOPOLOGY_STATE = 15, /* NUL-terminated string */
	NAMRBD_STATUS_ATTR_PATHS = 16, /* nested list of NAMRBD_STATUS_PATH_ATTR_* */
	NAMRBD_STATUS_ATTR_LANES = 17, /* nested list of NAMRBD_STATUS_LANE_ATTR_* */
	NAMRBD_STATUS_ATTR_LANE_REMAP_COUNT = 18, /* u64 */
	NAMRBD_STATUS_ATTR_LAST_LANE_REMAPPED_LANES = 19, /* u32 */
	NAMRBD_STATUS_ATTR_LAST_LANE_REMAP_JIFFIES = 20, /* u64 */
	NAMRBD_STATUS_ATTR_LAST_LANE_REMAP_REASON = 21, /* NUL-terminated string */
	NAMRBD_STATUS_ATTR_NO_PATH_RETRY_MODE = 22, /* u32 */
	NAMRBD_STATUS_ATTR_NO_PATH_RETRY_SECONDS = 23, /* u32 */
	NAMRBD_STATUS_ATTR_NO_PATH_STATE = 24, /* u32 */
	NAMRBD_STATUS_ATTR_NO_PATH_SINCE_JIFFIES = 25, /* u64 */
	NAMRBD_STATUS_ATTR_NO_PATH_RETRY_DEADLINE_JIFFIES = 26, /* u64 */
	NAMRBD_STATUS_ATTR_LAST_NO_PATH_WAKEUP_JIFFIES = 27, /* u64 */
	NAMRBD_STATUS_ATTR_NO_PATH_QUEUED_REQS = 28, /* u64 */
	NAMRBD_STATUS_ATTR_NO_PATH_REQUEUED_REQS = 29, /* u64 */
	NAMRBD_STATUS_ATTR_NO_PATH_FAILED_REQS = 30, /* u64 */
	NAMRBD_STATUS_ATTR_NO_PATH_RECOVERED_REQS = 31, /* u64 */
	NAMRBD_STATUS_ATTR_NO_PATH_ENTER_COUNT = 32, /* u64 */
	NAMRBD_STATUS_ATTR_LAST_NO_PATH_REASON = 33, /* u32 */
	NAMRBD_STATUS_ATTR_LAST_NO_PATH_OP = 34, /* u32 */
	NAMRBD_STATUS_ATTR_LAST_NO_PATH_ELIGIBLE_PATHS = 35, /* u32 */
	NAMRBD_STATUS_ATTR_LAST_NO_PATH_TRIED_MASK = 36, /* u64 */
	NAMRBD_STATUS_ATTR_LAST_NO_PATH_JIFFIES = 37, /* u64 */
	__NAMRBD_STATUS_ATTR_MAX,
};
#define NAMRBD_STATUS_ATTR_MAX (__NAMRBD_STATUS_ATTR_MAX - 1)

enum namrbd_status_path_attr {
	NAMRBD_STATUS_PATH_ATTR_UNSPEC = 0,
	NAMRBD_STATUS_PATH_ATTR_ENTRY = 1, /* nested */
	NAMRBD_STATUS_PATH_ATTR_PATH_ID = 2, /* u32 */
	NAMRBD_STATUS_PATH_ATTR_STATE = 3, /* u32 */
	NAMRBD_STATUS_PATH_ATTR_CONSECUTIVE_ERRORS = 4, /* u32 */
	NAMRBD_STATUS_PATH_ATTR_LAST_ERRNO = 5, /* u32 */
	NAMRBD_STATUS_PATH_ATTR_LAST_WIRE_STATUS = 6, /* u32 */
	NAMRBD_STATUS_PATH_ATTR_GATEWAY_ID = 7, /* NUL-terminated string */
	NAMRBD_STATUS_PATH_ATTR_ADDRESS = 8, /* NUL-terminated string */
	NAMRBD_STATUS_PATH_ATTR_PORT = 9, /* u16 */
	NAMRBD_STATUS_PATH_ATTR_USE_TLS = 10, /* u8 */
	NAMRBD_STATUS_PATH_ATTR_SERVER_NAME = 11, /* NUL-terminated string */
	NAMRBD_STATUS_PATH_ATTR_PRIORITY = 12, /* u32 */
	NAMRBD_STATUS_PATH_ATTR_CONNECTED = 13, /* u8 */
	NAMRBD_STATUS_PATH_ATTR_INFLIGHT = 14, /* u32 */
	NAMRBD_STATUS_PATH_ATTR_PENDING = 15, /* u32 */
	NAMRBD_STATUS_PATH_ATTR_OUTSTANDING_LIMIT = 16, /* u32 */
	NAMRBD_STATUS_PATH_ATTR_COMPLETED = 17, /* u64 */
	NAMRBD_STATUS_PATH_ATTR_RETRIES = 18, /* u64 */
	NAMRBD_STATUS_PATH_ATTR_CONN_OPENS = 19, /* u64 */
	NAMRBD_STATUS_PATH_ATTR_CONN_RESETS = 20, /* u64 */
	NAMRBD_STATUS_PATH_ATTR_PENDING_HIGH_WATER = 21, /* u32 */
	NAMRBD_STATUS_PATH_ATTR_SUBMITTED = 22, /* u64 */
	__NAMRBD_STATUS_PATH_ATTR_MAX,
};
#define NAMRBD_STATUS_PATH_ATTR_MAX (__NAMRBD_STATUS_PATH_ATTR_MAX - 1)

enum namrbd_status_lane_attr {
	NAMRBD_STATUS_LANE_ATTR_UNSPEC = 0,
	NAMRBD_STATUS_LANE_ATTR_ENTRY = 1, /* nested */
	NAMRBD_STATUS_LANE_ATTR_LANE_ID = 2, /* u32 */
	NAMRBD_STATUS_LANE_ATTR_PREFERRED_PATH_ID = 3, /* u32 */
	NAMRBD_STATUS_LANE_ATTR_FALLBACK_PATH_ID = 4, /* u32 */
	NAMRBD_STATUS_LANE_ATTR_READINESS = 5, /* u32 */
	NAMRBD_STATUS_LANE_ATTR_DISPATCH_REQS = 6, /* u64 */
	__NAMRBD_STATUS_LANE_ATTR_MAX,
};
#define NAMRBD_STATUS_LANE_ATTR_MAX (__NAMRBD_STATUS_LANE_ATTR_MAX - 1)

#endif /* _UAPI_NAMRBD_NETLINK_H_ */
