package envcompat

var (
	GatewayControlListen      = New("NAMRBD_GATEWAY_CONTROL_LISTEN", "NAMRBD_GATEWAY_LISTEN")
	GatewaySBSServiceEndpoint = New("NAMRBD_SBS_SERVICE_ENDPOINT", "NAMRBD_GATEWAY_SBS_ADMIN_ENDPOINT")

	SBSServiceNodeID     = New("NAMRBD_SBS_SERVICE_NODE_ID", "NAMRBD_NODE_ID")
	SBSServiceGRPCListen = New("NAMRBD_SBS_SERVICE_GRPC_LISTEN", "NAMRBD_SBS_ADMIN_ADDR")
	SBSServiceHTTPListen = New("NAMRBD_SBS_SERVICE_HTTP_LISTEN", "NAMRBD_BIND_ADDR")

	SBSDataPath       = New("NAMRBD_SBS_DATA_PATH", "NAMRBD_SBS_DATA_DIR")
	SBSDataGRPCListen = New("NAMRBD_SBS_DATA_GRPC_LISTEN", "NAMRBD_SBS_GRPC_ADDR")
	SBSDataHTTPListen = New("NAMRBD_SBS_DATA_HTTP_LISTEN", "NAMRBD_BIND_ADDR")

	ISCSISBSDataEndpoint    = New("NAMRBD_ISCSI_SBS_DATA_ENDPOINT", "NAMRBD_ISCSI_SBS_ENDPOINT")
	ISCSISBSServiceEndpoint = New("NAMRBD_ISCSI_SBS_SERVICE_ENDPOINT", "NAMRBD_ISCSI_SBS_ADMIN_ENDPOINT")

	CSISBSServiceEndpoint  = New("NAMRBD_SBS_SERVICE_ENDPOINT", "NAMRBD_ADMIN_ENDPOINT")
	CSISBSServiceEndpoints = New("NAMRBD_SBS_SERVICE_ENDPOINTS", "NAMRBD_ADMIN_ENDPOINTS")

	SBSClusterID              = New("NAMRBD_SBS_CLUSTER_ID", "SBS_CLUSTER_ID")
	SBSCTLServiceEndpoints    = New("NAMRBD_SBS_SERVICE_ENDPOINTS", "SBS_ADMIN_ENDPOINTS", "NAMRBD_SBS_ADMIN_ENDPOINTS")
	SBSCTLDataEndpoints       = New("NAMRBD_SBS_DATA_ENDPOINTS", "SBS_DATA_ENDPOINTS", "SBS_GRPC_ADDR", "NAMRBD_SBS_GRPC_ADDR")
	SBSCTLTimeout             = New("NAMRBD_SBSCTL_TIMEOUT", "SBS_TIMEOUT", "NAMRBD_TIMEOUT")
	SBSCTLOutput              = New("NAMRBD_SBSCTL_OUTPUT", "SBS_OUTPUT", "NAMRBD_OUTPUT")
	SBSCTLNodeID              = New("NAMRBD_SBS_NODE_ID", "SBS_NODE_ID", "NAMRBD_NODE_ID")
	SBSCTLZone                = New("NAMRBD_SBS_ZONE", "SBS_ZONE", "NAMRBD_ZONE")
	SBSCTLServiceHTTPEndpoint = New("NAMRBD_SBS_SERVICE_HTTP_ENDPOINT", "SBS_NODE_ADMIN_HTTP", "NAMRBD_SBS_ADMIN_ADDR")
)
