namespaceOverride: namrbd-system
createNamespace: true
driverName: csi.namrbd.io
edition: community

compatibility:
  enforceImmutableImages: true

image:
  repository: ghcr.io/nosway/namrbd-csi-driver
  tag: v1.0.0
  digest: sha256:e6a1e2111f896a54b725bb8f28e19461ad27bd8786d1f682d6ba1b34470fb958
  pullPolicy: IfNotPresent

sidecars:
  csiProvisioner:
    enabled: true
    image: registry.k8s.io/sig-storage/csi-provisioner:v5.1.0@sha256:672e45d6a55678abc1d102de665b5cbd63848e75dc7896f238c8eaaf3c7d322f
    timeout: 60s
  csiAttacher:
    enabled: true
    image: registry.k8s.io/sig-storage/csi-attacher:v4.8.1@sha256:69888dba58159c8bc0d7c092b9fb97900c9ca8710d088b0b7ea7bd9052df86f6
  csiSnapshotter:
    enabled: true
    image: registry.k8s.io/sig-storage/csi-snapshotter:v8.2.0@sha256:dd788d79cf4c1b8edee6d9b80b8a1ebfc51a38a365c5be656986b129be9ac784
  csiResizer:
    enabled: true
    image: registry.k8s.io/sig-storage/csi-resizer:v1.13.2@sha256:8ddd178ba5d08973f1607f9b84619b58320948de494b31c9d7cd5375b316d6d4
  nodeDriverRegistrar:
    enabled: true
    image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.13.0@sha256:d7138bcc3aa5f267403d45ad4292c95397e421ea17a0035888850f424c7de25d
  livenessProbe:
    enabled: true
    image: registry.k8s.io/sig-storage/livenessprobe:v2.15.0@sha256:2c5f9dc4ea5ac5509d93c664ae7982d4ecdec40ca7b0638c24e5b16243b8360f

controller:
  replicas: 1

node:
  enabled: true

config:
  clusterID: namrbd-community
  sbsClusterID: sbs-community
  adminEndpoint: namrbd-sbs-service:9897
  adminEndpoints: []
  gatewayURL: http://namrbd-gateway:9701
  socketDir: /csi
  kubeletRoot: /var/lib/kubelet

credentials:
  enabled: false
  existingSecret: namrbd-csi-credentials
  create: false
  bearerToken: ""
  tlsCaPem: ""

storageClasses:
  replicated:
    create: true
    name: namrbd-replicated
    reclaimPolicy: Delete
    volumeBindingMode: WaitForFirstConsumer
    allowVolumeExpansion: true
    discard:
      exposureState: disabled
      validationProfile: operator-validated
      mountOptions: []
    parameters:
      redundancy_backend: replicated
      replication_factor: "3"
      topology_mode: prefer
      block_size: "4K"
  ec63:
    create: false
    name: namrbd-ec-6-3
    reclaimPolicy: Delete
    volumeBindingMode: WaitForFirstConsumer
    allowVolumeExpansion: true
    discard:
      exposureState: disabled
      validationProfile: enterprise-validated
      mountOptions: []
    parameters:
      redundancy_backend: ec
      ec_profile: ec-6-3
      topology_mode: strict
      block_size: "4K"
      allocation_chunk_size: "128K"
      allocation_page_size: "4M"

volumeSnapshotClass:
  create: true
  name: namrbd-snapshot
  deletionPolicy: Delete
