// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: sbs/v1/volume.proto

package sbsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VolumeService_OpenVolume_FullMethodName         = "/sbs.v1.VolumeService/OpenVolume"
	VolumeService_CloseVolume_FullMethodName        = "/sbs.v1.VolumeService/CloseVolume"
	VolumeService_GetVolumeProfile_FullMethodName   = "/sbs.v1.VolumeService/GetVolumeProfile"
	VolumeService_GetVolumeStatus_FullMethodName    = "/sbs.v1.VolumeService/GetVolumeStatus"
	VolumeService_Read_FullMethodName               = "/sbs.v1.VolumeService/Read"
	VolumeService_Write_FullMethodName              = "/sbs.v1.VolumeService/Write"
	VolumeService_ReadPhysicalChunk_FullMethodName  = "/sbs.v1.VolumeService/ReadPhysicalChunk"
	VolumeService_WritePhysicalChunk_FullMethodName = "/sbs.v1.VolumeService/WritePhysicalChunk"
	VolumeService_WriteECShard_FullMethodName       = "/sbs.v1.VolumeService/WriteECShard"
	VolumeService_ReadECShard_FullMethodName        = "/sbs.v1.VolumeService/ReadECShard"
	VolumeService_DeleteECShard_FullMethodName      = "/sbs.v1.VolumeService/DeleteECShard"
	VolumeService_Flush_FullMethodName              = "/sbs.v1.VolumeService/Flush"
	VolumeService_Discard_FullMethodName            = "/sbs.v1.VolumeService/Discard"
	VolumeService_Zero_FullMethodName               = "/sbs.v1.VolumeService/Zero"
)

// VolumeServiceClient is the client API for VolumeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VolumeServiceClient interface {
	OpenVolume(ctx context.Context, in *OpenVolumeRequest, opts ...grpc.CallOption) (*OpenVolumeResponse, error)
	CloseVolume(ctx context.Context, in *CloseVolumeRequest, opts ...grpc.CallOption) (*CloseVolumeResponse, error)
	GetVolumeProfile(ctx context.Context, in *GetVolumeProfileRequest, opts ...grpc.CallOption) (*GetVolumeProfileResponse, error)
	GetVolumeStatus(ctx context.Context, in *GetVolumeStatusRequest, opts ...grpc.CallOption) (*GetVolumeStatusResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error)
	ReadPhysicalChunk(ctx context.Context, in *ReadPhysicalChunkRequest, opts ...grpc.CallOption) (*ReadPhysicalChunkResponse, error)
	WritePhysicalChunk(ctx context.Context, in *WritePhysicalChunkRequest, opts ...grpc.CallOption) (*WritePhysicalChunkResponse, error)
	WriteECShard(ctx context.Context, in *WriteECShardRequest, opts ...grpc.CallOption) (*WriteECShardResponse, error)
	ReadECShard(ctx context.Context, in *ReadECShardRequest, opts ...grpc.CallOption) (*ReadECShardResponse, error)
	DeleteECShard(ctx context.Context, in *DeleteECShardRequest, opts ...grpc.CallOption) (*DeleteECShardResponse, error)
	Flush(ctx context.Context, in *FlushRequest, opts ...grpc.CallOption) (*FlushResponse, error)
	Discard(ctx context.Context, in *DiscardRequest, opts ...grpc.CallOption) (*DiscardResponse, error)
	Zero(ctx context.Context, in *ZeroRequest, opts ...grpc.CallOption) (*ZeroResponse, error)
}

type volumeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVolumeServiceClient(cc grpc.ClientConnInterface) VolumeServiceClient {
	return &volumeServiceClient{cc}
}

func (c *volumeServiceClient) OpenVolume(ctx context.Context, in *OpenVolumeRequest, opts ...grpc.CallOption) (*OpenVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenVolumeResponse)
	err := c.cc.Invoke(ctx, VolumeService_OpenVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeServiceClient) CloseVolume(ctx context.Context, in *CloseVolumeRequest, opts ...grpc.CallOption) (*CloseVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseVolumeResponse)
	err := c.cc.Invoke(ctx, VolumeService_CloseVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeServiceClient) GetVolumeProfile(ctx context.Context, in *GetVolumeProfileRequest, opts ...grpc.CallOption) (*GetVolumeProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVolumeProfileResponse)
	err := c.cc.Invoke(ctx, VolumeService_GetVolumeProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeServiceClient) GetVolumeStatus(ctx context.Context, in *GetVolumeStatusRequest, opts ...grpc.CallOption) (*GetVolumeStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVolumeStatusResponse)
	err := c.cc.Invoke(ctx, VolumeService_GetVolumeStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeServiceClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, VolumeService_Read_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeServiceClient) Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteResponse)
	err := c.cc.Invoke(ctx, VolumeService_Write_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeServiceClient) ReadPhysicalChunk(ctx context.Context, in *ReadPhysicalChunkRequest, opts ...grpc.CallOption) (*ReadPhysicalChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadPhysicalChunkResponse)
	err := c.cc.Invoke(ctx, VolumeService_ReadPhysicalChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeServiceClient) WritePhysicalChunk(ctx context.Context, in *WritePhysicalChunkRequest, opts ...grpc.CallOption) (*WritePhysicalChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WritePhysicalChunkResponse)
	err := c.cc.Invoke(ctx, VolumeService_WritePhysicalChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeServiceClient) WriteECShard(ctx context.Context, in *WriteECShardRequest, opts ...grpc.CallOption) (*WriteECShardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteECShardResponse)
	err := c.cc.Invoke(ctx, VolumeService_WriteECShard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeServiceClient) ReadECShard(ctx context.Context, in *ReadECShardRequest, opts ...grpc.CallOption) (*ReadECShardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadECShardResponse)
	err := c.cc.Invoke(ctx, VolumeService_ReadECShard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeServiceClient) DeleteECShard(ctx context.Context, in *DeleteECShardRequest, opts ...grpc.CallOption) (*DeleteECShardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteECShardResponse)
	err := c.cc.Invoke(ctx, VolumeService_DeleteECShard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeServiceClient) Flush(ctx context.Context, in *FlushRequest, opts ...grpc.CallOption) (*FlushResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlushResponse)
	err := c.cc.Invoke(ctx, VolumeService_Flush_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeServiceClient) Discard(ctx context.Context, in *DiscardRequest, opts ...grpc.CallOption) (*DiscardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscardResponse)
	err := c.cc.Invoke(ctx, VolumeService_Discard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeServiceClient) Zero(ctx context.Context, in *ZeroRequest, opts ...grpc.CallOption) (*ZeroResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ZeroResponse)
	err := c.cc.Invoke(ctx, VolumeService_Zero_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VolumeServiceServer is the server API for VolumeService service.
// All implementations must embed UnimplementedVolumeServiceServer
// for forward compatibility.
type VolumeServiceServer interface {
	OpenVolume(context.Context, *OpenVolumeRequest) (*OpenVolumeResponse, error)
	CloseVolume(context.Context, *CloseVolumeRequest) (*CloseVolumeResponse, error)
	GetVolumeProfile(context.Context, *GetVolumeProfileRequest) (*GetVolumeProfileResponse, error)
	GetVolumeStatus(context.Context, *GetVolumeStatusRequest) (*GetVolumeStatusResponse, error)
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
	Write(context.Context, *WriteRequest) (*WriteResponse, error)
	ReadPhysicalChunk(context.Context, *ReadPhysicalChunkRequest) (*ReadPhysicalChunkResponse, error)
	WritePhysicalChunk(context.Context, *WritePhysicalChunkRequest) (*WritePhysicalChunkResponse, error)
	WriteECShard(context.Context, *WriteECShardRequest) (*WriteECShardResponse, error)
	ReadECShard(context.Context, *ReadECShardRequest) (*ReadECShardResponse, error)
	DeleteECShard(context.Context, *DeleteECShardRequest) (*DeleteECShardResponse, error)
	Flush(context.Context, *FlushRequest) (*FlushResponse, error)
	Discard(context.Context, *DiscardRequest) (*DiscardResponse, error)
	Zero(context.Context, *ZeroRequest) (*ZeroResponse, error)
	mustEmbedUnimplementedVolumeServiceServer()
}

// UnimplementedVolumeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVolumeServiceServer struct{}

func (UnimplementedVolumeServiceServer) OpenVolume(context.Context, *OpenVolumeRequest) (*OpenVolumeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenVolume not implemented")
}
func (UnimplementedVolumeServiceServer) CloseVolume(context.Context, *CloseVolumeRequest) (*CloseVolumeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseVolume not implemented")
}
func (UnimplementedVolumeServiceServer) GetVolumeProfile(context.Context, *GetVolumeProfileRequest) (*GetVolumeProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVolumeProfile not implemented")
}
func (UnimplementedVolumeServiceServer) GetVolumeStatus(context.Context, *GetVolumeStatusRequest) (*GetVolumeStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVolumeStatus not implemented")
}
func (UnimplementedVolumeServiceServer) Read(context.Context, *ReadRequest) (*ReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedVolumeServiceServer) Write(context.Context, *WriteRequest) (*WriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedVolumeServiceServer) ReadPhysicalChunk(context.Context, *ReadPhysicalChunkRequest) (*ReadPhysicalChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadPhysicalChunk not implemented")
}
func (UnimplementedVolumeServiceServer) WritePhysicalChunk(context.Context, *WritePhysicalChunkRequest) (*WritePhysicalChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WritePhysicalChunk not implemented")
}
func (UnimplementedVolumeServiceServer) WriteECShard(context.Context, *WriteECShardRequest) (*WriteECShardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteECShard not implemented")
}
func (UnimplementedVolumeServiceServer) ReadECShard(context.Context, *ReadECShardRequest) (*ReadECShardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadECShard not implemented")
}
func (UnimplementedVolumeServiceServer) DeleteECShard(context.Context, *DeleteECShardRequest) (*DeleteECShardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteECShard not implemented")
}
func (UnimplementedVolumeServiceServer) Flush(context.Context, *FlushRequest) (*FlushResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Flush not implemented")
}
func (UnimplementedVolumeServiceServer) Discard(context.Context, *DiscardRequest) (*DiscardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Discard not implemented")
}
func (UnimplementedVolumeServiceServer) Zero(context.Context, *ZeroRequest) (*ZeroResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Zero not implemented")
}
func (UnimplementedVolumeServiceServer) mustEmbedUnimplementedVolumeServiceServer() {}
func (UnimplementedVolumeServiceServer) testEmbeddedByValue()                       {}

// UnsafeVolumeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VolumeServiceServer will
// result in compilation errors.
type UnsafeVolumeServiceServer interface {
	mustEmbedUnimplementedVolumeServiceServer()
}

func RegisterVolumeServiceServer(s grpc.ServiceRegistrar, srv VolumeServiceServer) {
	// If the following call pancis, it indicates UnimplementedVolumeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VolumeService_ServiceDesc, srv)
}

func _VolumeService_OpenVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServiceServer).OpenVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolumeService_OpenVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServiceServer).OpenVolume(ctx, req.(*OpenVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumeService_CloseVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServiceServer).CloseVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolumeService_CloseVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServiceServer).CloseVolume(ctx, req.(*CloseVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumeService_GetVolumeProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVolumeProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServiceServer).GetVolumeProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolumeService_GetVolumeProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServiceServer).GetVolumeProfile(ctx, req.(*GetVolumeProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumeService_GetVolumeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVolumeStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServiceServer).GetVolumeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolumeService_GetVolumeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServiceServer).GetVolumeStatus(ctx, req.(*GetVolumeStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumeService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolumeService_Read_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServiceServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumeService_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServiceServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolumeService_Write_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServiceServer).Write(ctx, req.(*WriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumeService_ReadPhysicalChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadPhysicalChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServiceServer).ReadPhysicalChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolumeService_ReadPhysicalChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServiceServer).ReadPhysicalChunk(ctx, req.(*ReadPhysicalChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumeService_WritePhysicalChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WritePhysicalChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServiceServer).WritePhysicalChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolumeService_WritePhysicalChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServiceServer).WritePhysicalChunk(ctx, req.(*WritePhysicalChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumeService_WriteECShard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteECShardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServiceServer).WriteECShard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolumeService_WriteECShard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServiceServer).WriteECShard(ctx, req.(*WriteECShardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumeService_ReadECShard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadECShardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServiceServer).ReadECShard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolumeService_ReadECShard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServiceServer).ReadECShard(ctx, req.(*ReadECShardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumeService_DeleteECShard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteECShardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServiceServer).DeleteECShard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolumeService_DeleteECShard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServiceServer).DeleteECShard(ctx, req.(*DeleteECShardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumeService_Flush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServiceServer).Flush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolumeService_Flush_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServiceServer).Flush(ctx, req.(*FlushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumeService_Discard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServiceServer).Discard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolumeService_Discard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServiceServer).Discard(ctx, req.(*DiscardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumeService_Zero_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZeroRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServiceServer).Zero(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolumeService_Zero_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServiceServer).Zero(ctx, req.(*ZeroRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VolumeService_ServiceDesc is the grpc.ServiceDesc for VolumeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VolumeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sbs.v1.VolumeService",
	HandlerType: (*VolumeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenVolume",
			Handler:    _VolumeService_OpenVolume_Handler,
		},
		{
			MethodName: "CloseVolume",
			Handler:    _VolumeService_CloseVolume_Handler,
		},
		{
			MethodName: "GetVolumeProfile",
			Handler:    _VolumeService_GetVolumeProfile_Handler,
		},
		{
			MethodName: "GetVolumeStatus",
			Handler:    _VolumeService_GetVolumeStatus_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _VolumeService_Read_Handler,
		},
		{
			MethodName: "Write",
			Handler:    _VolumeService_Write_Handler,
		},
		{
			MethodName: "ReadPhysicalChunk",
			Handler:    _VolumeService_ReadPhysicalChunk_Handler,
		},
		{
			MethodName: "WritePhysicalChunk",
			Handler:    _VolumeService_WritePhysicalChunk_Handler,
		},
		{
			MethodName: "WriteECShard",
			Handler:    _VolumeService_WriteECShard_Handler,
		},
		{
			MethodName: "ReadECShard",
			Handler:    _VolumeService_ReadECShard_Handler,
		},
		{
			MethodName: "DeleteECShard",
			Handler:    _VolumeService_DeleteECShard_Handler,
		},
		{
			MethodName: "Flush",
			Handler:    _VolumeService_Flush_Handler,
		},
		{
			MethodName: "Discard",
			Handler:    _VolumeService_Discard_Handler,
		},
		{
			MethodName: "Zero",
			Handler:    _VolumeService_Zero_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sbs/v1/volume.proto",
}
