apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: namrbd-demo-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  storageClassName: namrbd-replicated
  resources:
    requests:
      storage: 8Mi
