// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: sbs/internalapi/v1/chunk_id_allocator.proto

package internalv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChunkIDAllocatorService_AllocateChunkIDs_FullMethodName = "/sbs.internalapi.v1.ChunkIDAllocatorService/AllocateChunkIDs"
)

// ChunkIDAllocatorServiceClient is the client API for ChunkIDAllocatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ChunkIDAllocatorService is an internal-only authority surface for allocating
// monotonic physical chunk IDs owned by sbs-service.
type ChunkIDAllocatorServiceClient interface {
	AllocateChunkIDs(ctx context.Context, in *AllocateChunkIDsRequest, opts ...grpc.CallOption) (*AllocateChunkIDsResponse, error)
}

type chunkIDAllocatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChunkIDAllocatorServiceClient(cc grpc.ClientConnInterface) ChunkIDAllocatorServiceClient {
	return &chunkIDAllocatorServiceClient{cc}
}

func (c *chunkIDAllocatorServiceClient) AllocateChunkIDs(ctx context.Context, in *AllocateChunkIDsRequest, opts ...grpc.CallOption) (*AllocateChunkIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllocateChunkIDsResponse)
	err := c.cc.Invoke(ctx, ChunkIDAllocatorService_AllocateChunkIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChunkIDAllocatorServiceServer is the server API for ChunkIDAllocatorService service.
// All implementations must embed UnimplementedChunkIDAllocatorServiceServer
// for forward compatibility.
//
// ChunkIDAllocatorService is an internal-only authority surface for allocating
// monotonic physical chunk IDs owned by sbs-service.
type ChunkIDAllocatorServiceServer interface {
	AllocateChunkIDs(context.Context, *AllocateChunkIDsRequest) (*AllocateChunkIDsResponse, error)
	mustEmbedUnimplementedChunkIDAllocatorServiceServer()
}

// UnimplementedChunkIDAllocatorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChunkIDAllocatorServiceServer struct{}

func (UnimplementedChunkIDAllocatorServiceServer) AllocateChunkIDs(context.Context, *AllocateChunkIDsRequest) (*AllocateChunkIDsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllocateChunkIDs not implemented")
}
func (UnimplementedChunkIDAllocatorServiceServer) mustEmbedUnimplementedChunkIDAllocatorServiceServer() {
}
func (UnimplementedChunkIDAllocatorServiceServer) testEmbeddedByValue() {}

// UnsafeChunkIDAllocatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChunkIDAllocatorServiceServer will
// result in compilation errors.
type UnsafeChunkIDAllocatorServiceServer interface {
	mustEmbedUnimplementedChunkIDAllocatorServiceServer()
}

func RegisterChunkIDAllocatorServiceServer(s grpc.ServiceRegistrar, srv ChunkIDAllocatorServiceServer) {
	// If the following call pancis, it indicates UnimplementedChunkIDAllocatorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChunkIDAllocatorService_ServiceDesc, srv)
}

func _ChunkIDAllocatorService_AllocateChunkIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocateChunkIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkIDAllocatorServiceServer).AllocateChunkIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkIDAllocatorService_AllocateChunkIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkIDAllocatorServiceServer).AllocateChunkIDs(ctx, req.(*AllocateChunkIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChunkIDAllocatorService_ServiceDesc is the grpc.ServiceDesc for ChunkIDAllocatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChunkIDAllocatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sbs.internalapi.v1.ChunkIDAllocatorService",
	HandlerType: (*ChunkIDAllocatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AllocateChunkIDs",
			Handler:    _ChunkIDAllocatorService_AllocateChunkIDs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sbs/internalapi/v1/chunk_id_allocator.proto",
}
