// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: sbs/internalapi/v1/ec_metadata.proto

package internalv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ECMetadataService_GetPhysicalObject_FullMethodName       = "/sbs.internalapi.v1.ECMetadataService/GetPhysicalObject"
	ECMetadataService_PutPhysicalObject_FullMethodName       = "/sbs.internalapi.v1.ECMetadataService/PutPhysicalObject"
	ECMetadataService_GetECStripe_FullMethodName             = "/sbs.internalapi.v1.ECMetadataService/GetECStripe"
	ECMetadataService_PutECStripe_FullMethodName             = "/sbs.internalapi.v1.ECMetadataService/PutECStripe"
	ECMetadataService_CommitECFullStripeWrite_FullMethodName = "/sbs.internalapi.v1.ECMetadataService/CommitECFullStripeWrite"
	ECMetadataService_CommitECDiscard_FullMethodName         = "/sbs.internalapi.v1.ECMetadataService/CommitECDiscard"
)

// ECMetadataServiceClient is the client API for ECMetadataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ECMetadataServiceClient interface {
	GetPhysicalObject(ctx context.Context, in *GetPhysicalObjectRequest, opts ...grpc.CallOption) (*GetPhysicalObjectResponse, error)
	PutPhysicalObject(ctx context.Context, in *PutPhysicalObjectRequest, opts ...grpc.CallOption) (*PutPhysicalObjectResponse, error)
	GetECStripe(ctx context.Context, in *GetECStripeRequest, opts ...grpc.CallOption) (*GetECStripeResponse, error)
	PutECStripe(ctx context.Context, in *PutECStripeRequest, opts ...grpc.CallOption) (*PutECStripeResponse, error)
	CommitECFullStripeWrite(ctx context.Context, in *CommitECFullStripeWriteRequest, opts ...grpc.CallOption) (*CommitECFullStripeWriteResponse, error)
	CommitECDiscard(ctx context.Context, in *CommitECDiscardRequest, opts ...grpc.CallOption) (*CommitECDiscardResponse, error)
}

type eCMetadataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewECMetadataServiceClient(cc grpc.ClientConnInterface) ECMetadataServiceClient {
	return &eCMetadataServiceClient{cc}
}

func (c *eCMetadataServiceClient) GetPhysicalObject(ctx context.Context, in *GetPhysicalObjectRequest, opts ...grpc.CallOption) (*GetPhysicalObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPhysicalObjectResponse)
	err := c.cc.Invoke(ctx, ECMetadataService_GetPhysicalObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eCMetadataServiceClient) PutPhysicalObject(ctx context.Context, in *PutPhysicalObjectRequest, opts ...grpc.CallOption) (*PutPhysicalObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutPhysicalObjectResponse)
	err := c.cc.Invoke(ctx, ECMetadataService_PutPhysicalObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eCMetadataServiceClient) GetECStripe(ctx context.Context, in *GetECStripeRequest, opts ...grpc.CallOption) (*GetECStripeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetECStripeResponse)
	err := c.cc.Invoke(ctx, ECMetadataService_GetECStripe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eCMetadataServiceClient) PutECStripe(ctx context.Context, in *PutECStripeRequest, opts ...grpc.CallOption) (*PutECStripeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutECStripeResponse)
	err := c.cc.Invoke(ctx, ECMetadataService_PutECStripe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eCMetadataServiceClient) CommitECFullStripeWrite(ctx context.Context, in *CommitECFullStripeWriteRequest, opts ...grpc.CallOption) (*CommitECFullStripeWriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitECFullStripeWriteResponse)
	err := c.cc.Invoke(ctx, ECMetadataService_CommitECFullStripeWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eCMetadataServiceClient) CommitECDiscard(ctx context.Context, in *CommitECDiscardRequest, opts ...grpc.CallOption) (*CommitECDiscardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitECDiscardResponse)
	err := c.cc.Invoke(ctx, ECMetadataService_CommitECDiscard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ECMetadataServiceServer is the server API for ECMetadataService service.
// All implementations must embed UnimplementedECMetadataServiceServer
// for forward compatibility.
type ECMetadataServiceServer interface {
	GetPhysicalObject(context.Context, *GetPhysicalObjectRequest) (*GetPhysicalObjectResponse, error)
	PutPhysicalObject(context.Context, *PutPhysicalObjectRequest) (*PutPhysicalObjectResponse, error)
	GetECStripe(context.Context, *GetECStripeRequest) (*GetECStripeResponse, error)
	PutECStripe(context.Context, *PutECStripeRequest) (*PutECStripeResponse, error)
	CommitECFullStripeWrite(context.Context, *CommitECFullStripeWriteRequest) (*CommitECFullStripeWriteResponse, error)
	CommitECDiscard(context.Context, *CommitECDiscardRequest) (*CommitECDiscardResponse, error)
	mustEmbedUnimplementedECMetadataServiceServer()
}

// UnimplementedECMetadataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedECMetadataServiceServer struct{}

func (UnimplementedECMetadataServiceServer) GetPhysicalObject(context.Context, *GetPhysicalObjectRequest) (*GetPhysicalObjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPhysicalObject not implemented")
}
func (UnimplementedECMetadataServiceServer) PutPhysicalObject(context.Context, *PutPhysicalObjectRequest) (*PutPhysicalObjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutPhysicalObject not implemented")
}
func (UnimplementedECMetadataServiceServer) GetECStripe(context.Context, *GetECStripeRequest) (*GetECStripeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetECStripe not implemented")
}
func (UnimplementedECMetadataServiceServer) PutECStripe(context.Context, *PutECStripeRequest) (*PutECStripeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutECStripe not implemented")
}
func (UnimplementedECMetadataServiceServer) CommitECFullStripeWrite(context.Context, *CommitECFullStripeWriteRequest) (*CommitECFullStripeWriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitECFullStripeWrite not implemented")
}
func (UnimplementedECMetadataServiceServer) CommitECDiscard(context.Context, *CommitECDiscardRequest) (*CommitECDiscardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitECDiscard not implemented")
}
func (UnimplementedECMetadataServiceServer) mustEmbedUnimplementedECMetadataServiceServer() {}
func (UnimplementedECMetadataServiceServer) testEmbeddedByValue()                           {}

// UnsafeECMetadataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ECMetadataServiceServer will
// result in compilation errors.
type UnsafeECMetadataServiceServer interface {
	mustEmbedUnimplementedECMetadataServiceServer()
}

func RegisterECMetadataServiceServer(s grpc.ServiceRegistrar, srv ECMetadataServiceServer) {
	// If the following call pancis, it indicates UnimplementedECMetadataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ECMetadataService_ServiceDesc, srv)
}

func _ECMetadataService_GetPhysicalObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPhysicalObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ECMetadataServiceServer).GetPhysicalObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ECMetadataService_GetPhysicalObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ECMetadataServiceServer).GetPhysicalObject(ctx, req.(*GetPhysicalObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ECMetadataService_PutPhysicalObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutPhysicalObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ECMetadataServiceServer).PutPhysicalObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ECMetadataService_PutPhysicalObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ECMetadataServiceServer).PutPhysicalObject(ctx, req.(*PutPhysicalObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ECMetadataService_GetECStripe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetECStripeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ECMetadataServiceServer).GetECStripe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ECMetadataService_GetECStripe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ECMetadataServiceServer).GetECStripe(ctx, req.(*GetECStripeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ECMetadataService_PutECStripe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutECStripeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ECMetadataServiceServer).PutECStripe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ECMetadataService_PutECStripe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ECMetadataServiceServer).PutECStripe(ctx, req.(*PutECStripeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ECMetadataService_CommitECFullStripeWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitECFullStripeWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ECMetadataServiceServer).CommitECFullStripeWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ECMetadataService_CommitECFullStripeWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ECMetadataServiceServer).CommitECFullStripeWrite(ctx, req.(*CommitECFullStripeWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ECMetadataService_CommitECDiscard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitECDiscardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ECMetadataServiceServer).CommitECDiscard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ECMetadataService_CommitECDiscard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ECMetadataServiceServer).CommitECDiscard(ctx, req.(*CommitECDiscardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ECMetadataService_ServiceDesc is the grpc.ServiceDesc for ECMetadataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ECMetadataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sbs.internalapi.v1.ECMetadataService",
	HandlerType: (*ECMetadataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPhysicalObject",
			Handler:    _ECMetadataService_GetPhysicalObject_Handler,
		},
		{
			MethodName: "PutPhysicalObject",
			Handler:    _ECMetadataService_PutPhysicalObject_Handler,
		},
		{
			MethodName: "GetECStripe",
			Handler:    _ECMetadataService_GetECStripe_Handler,
		},
		{
			MethodName: "PutECStripe",
			Handler:    _ECMetadataService_PutECStripe_Handler,
		},
		{
			MethodName: "CommitECFullStripeWrite",
			Handler:    _ECMetadataService_CommitECFullStripeWrite_Handler,
		},
		{
			MethodName: "CommitECDiscard",
			Handler:    _ECMetadataService_CommitECDiscard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sbs/internalapi/v1/ec_metadata.proto",
}
