// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: sbs/internalapi/v1/persistent_reservation.proto

package internalv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PersistentReservationAuthorityService_IssuePersistentReservationToken_FullMethodName  = "/sbs.internalapi.v1.PersistentReservationAuthorityService/IssuePersistentReservationToken"
	PersistentReservationAuthorityService_CheckPersistentReservationAccess_FullMethodName = "/sbs.internalapi.v1.PersistentReservationAuthorityService/CheckPersistentReservationAccess"
)

// PersistentReservationAuthorityServiceClient is the client API for PersistentReservationAuthorityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PersistentReservationAuthorityService is an internal, fail-closed authority
// used by protocol targets. Tokens capture the durable PR generation at
// connect time and every I/O rechecks that generation and access mode.
type PersistentReservationAuthorityServiceClient interface {
	IssuePersistentReservationToken(ctx context.Context, in *IssuePersistentReservationTokenRequest, opts ...grpc.CallOption) (*IssuePersistentReservationTokenResponse, error)
	CheckPersistentReservationAccess(ctx context.Context, in *CheckPersistentReservationAccessRequest, opts ...grpc.CallOption) (*CheckPersistentReservationAccessResponse, error)
}

type persistentReservationAuthorityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPersistentReservationAuthorityServiceClient(cc grpc.ClientConnInterface) PersistentReservationAuthorityServiceClient {
	return &persistentReservationAuthorityServiceClient{cc}
}

func (c *persistentReservationAuthorityServiceClient) IssuePersistentReservationToken(ctx context.Context, in *IssuePersistentReservationTokenRequest, opts ...grpc.CallOption) (*IssuePersistentReservationTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssuePersistentReservationTokenResponse)
	err := c.cc.Invoke(ctx, PersistentReservationAuthorityService_IssuePersistentReservationToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistentReservationAuthorityServiceClient) CheckPersistentReservationAccess(ctx context.Context, in *CheckPersistentReservationAccessRequest, opts ...grpc.CallOption) (*CheckPersistentReservationAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckPersistentReservationAccessResponse)
	err := c.cc.Invoke(ctx, PersistentReservationAuthorityService_CheckPersistentReservationAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PersistentReservationAuthorityServiceServer is the server API for PersistentReservationAuthorityService service.
// All implementations must embed UnimplementedPersistentReservationAuthorityServiceServer
// for forward compatibility.
//
// PersistentReservationAuthorityService is an internal, fail-closed authority
// used by protocol targets. Tokens capture the durable PR generation at
// connect time and every I/O rechecks that generation and access mode.
type PersistentReservationAuthorityServiceServer interface {
	IssuePersistentReservationToken(context.Context, *IssuePersistentReservationTokenRequest) (*IssuePersistentReservationTokenResponse, error)
	CheckPersistentReservationAccess(context.Context, *CheckPersistentReservationAccessRequest) (*CheckPersistentReservationAccessResponse, error)
	mustEmbedUnimplementedPersistentReservationAuthorityServiceServer()
}

// UnimplementedPersistentReservationAuthorityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPersistentReservationAuthorityServiceServer struct{}

func (UnimplementedPersistentReservationAuthorityServiceServer) IssuePersistentReservationToken(context.Context, *IssuePersistentReservationTokenRequest) (*IssuePersistentReservationTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssuePersistentReservationToken not implemented")
}
func (UnimplementedPersistentReservationAuthorityServiceServer) CheckPersistentReservationAccess(context.Context, *CheckPersistentReservationAccessRequest) (*CheckPersistentReservationAccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckPersistentReservationAccess not implemented")
}
func (UnimplementedPersistentReservationAuthorityServiceServer) mustEmbedUnimplementedPersistentReservationAuthorityServiceServer() {
}
func (UnimplementedPersistentReservationAuthorityServiceServer) testEmbeddedByValue() {}

// UnsafePersistentReservationAuthorityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PersistentReservationAuthorityServiceServer will
// result in compilation errors.
type UnsafePersistentReservationAuthorityServiceServer interface {
	mustEmbedUnimplementedPersistentReservationAuthorityServiceServer()
}

func RegisterPersistentReservationAuthorityServiceServer(s grpc.ServiceRegistrar, srv PersistentReservationAuthorityServiceServer) {
	// If the following call pancis, it indicates UnimplementedPersistentReservationAuthorityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PersistentReservationAuthorityService_ServiceDesc, srv)
}

func _PersistentReservationAuthorityService_IssuePersistentReservationToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssuePersistentReservationTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistentReservationAuthorityServiceServer).IssuePersistentReservationToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PersistentReservationAuthorityService_IssuePersistentReservationToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistentReservationAuthorityServiceServer).IssuePersistentReservationToken(ctx, req.(*IssuePersistentReservationTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersistentReservationAuthorityService_CheckPersistentReservationAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPersistentReservationAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistentReservationAuthorityServiceServer).CheckPersistentReservationAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PersistentReservationAuthorityService_CheckPersistentReservationAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistentReservationAuthorityServiceServer).CheckPersistentReservationAccess(ctx, req.(*CheckPersistentReservationAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PersistentReservationAuthorityService_ServiceDesc is the grpc.ServiceDesc for PersistentReservationAuthorityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PersistentReservationAuthorityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sbs.internalapi.v1.PersistentReservationAuthorityService",
	HandlerType: (*PersistentReservationAuthorityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IssuePersistentReservationToken",
			Handler:    _PersistentReservationAuthorityService_IssuePersistentReservationToken_Handler,
		},
		{
			MethodName: "CheckPersistentReservationAccess",
			Handler:    _PersistentReservationAuthorityService_CheckPersistentReservationAccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sbs/internalapi/v1/persistent_reservation.proto",
}
