// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: sbs/internalapi/v1/placement_resolver.proto

package internalv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlacementResolverService_ResolveExtentPlacements_FullMethodName        = "/sbs.internalapi.v1.PlacementResolverService/ResolveExtentPlacements"
	PlacementResolverService_ResolveAllocationPages_FullMethodName         = "/sbs.internalapi.v1.PlacementResolverService/ResolveAllocationPages"
	PlacementResolverService_ResolveSnapshotAllocationPages_FullMethodName = "/sbs.internalapi.v1.PlacementResolverService/ResolveSnapshotAllocationPages"
	PlacementResolverService_ResolveCloneAllocationPages_FullMethodName    = "/sbs.internalapi.v1.PlacementResolverService/ResolveCloneAllocationPages"
)

// PlacementResolverServiceClient is the client API for PlacementResolverService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PlacementResolverService is an internal-only read surface for placement and
// allocation planning inputs owned by sbs-service.
type PlacementResolverServiceClient interface {
	ResolveExtentPlacements(ctx context.Context, in *ResolveExtentPlacementsRequest, opts ...grpc.CallOption) (*ResolveExtentPlacementsResponse, error)
	ResolveAllocationPages(ctx context.Context, in *ResolveAllocationPagesRequest, opts ...grpc.CallOption) (*ResolveAllocationPagesResponse, error)
	ResolveSnapshotAllocationPages(ctx context.Context, in *ResolveSnapshotAllocationPagesRequest, opts ...grpc.CallOption) (*ResolveSnapshotAllocationPagesResponse, error)
	ResolveCloneAllocationPages(ctx context.Context, in *ResolveCloneAllocationPagesRequest, opts ...grpc.CallOption) (*ResolveCloneAllocationPagesResponse, error)
}

type placementResolverServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlacementResolverServiceClient(cc grpc.ClientConnInterface) PlacementResolverServiceClient {
	return &placementResolverServiceClient{cc}
}

func (c *placementResolverServiceClient) ResolveExtentPlacements(ctx context.Context, in *ResolveExtentPlacementsRequest, opts ...grpc.CallOption) (*ResolveExtentPlacementsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveExtentPlacementsResponse)
	err := c.cc.Invoke(ctx, PlacementResolverService_ResolveExtentPlacements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *placementResolverServiceClient) ResolveAllocationPages(ctx context.Context, in *ResolveAllocationPagesRequest, opts ...grpc.CallOption) (*ResolveAllocationPagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveAllocationPagesResponse)
	err := c.cc.Invoke(ctx, PlacementResolverService_ResolveAllocationPages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *placementResolverServiceClient) ResolveSnapshotAllocationPages(ctx context.Context, in *ResolveSnapshotAllocationPagesRequest, opts ...grpc.CallOption) (*ResolveSnapshotAllocationPagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveSnapshotAllocationPagesResponse)
	err := c.cc.Invoke(ctx, PlacementResolverService_ResolveSnapshotAllocationPages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *placementResolverServiceClient) ResolveCloneAllocationPages(ctx context.Context, in *ResolveCloneAllocationPagesRequest, opts ...grpc.CallOption) (*ResolveCloneAllocationPagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveCloneAllocationPagesResponse)
	err := c.cc.Invoke(ctx, PlacementResolverService_ResolveCloneAllocationPages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlacementResolverServiceServer is the server API for PlacementResolverService service.
// All implementations must embed UnimplementedPlacementResolverServiceServer
// for forward compatibility.
//
// PlacementResolverService is an internal-only read surface for placement and
// allocation planning inputs owned by sbs-service.
type PlacementResolverServiceServer interface {
	ResolveExtentPlacements(context.Context, *ResolveExtentPlacementsRequest) (*ResolveExtentPlacementsResponse, error)
	ResolveAllocationPages(context.Context, *ResolveAllocationPagesRequest) (*ResolveAllocationPagesResponse, error)
	ResolveSnapshotAllocationPages(context.Context, *ResolveSnapshotAllocationPagesRequest) (*ResolveSnapshotAllocationPagesResponse, error)
	ResolveCloneAllocationPages(context.Context, *ResolveCloneAllocationPagesRequest) (*ResolveCloneAllocationPagesResponse, error)
	mustEmbedUnimplementedPlacementResolverServiceServer()
}

// UnimplementedPlacementResolverServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlacementResolverServiceServer struct{}

func (UnimplementedPlacementResolverServiceServer) ResolveExtentPlacements(context.Context, *ResolveExtentPlacementsRequest) (*ResolveExtentPlacementsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveExtentPlacements not implemented")
}
func (UnimplementedPlacementResolverServiceServer) ResolveAllocationPages(context.Context, *ResolveAllocationPagesRequest) (*ResolveAllocationPagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveAllocationPages not implemented")
}
func (UnimplementedPlacementResolverServiceServer) ResolveSnapshotAllocationPages(context.Context, *ResolveSnapshotAllocationPagesRequest) (*ResolveSnapshotAllocationPagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveSnapshotAllocationPages not implemented")
}
func (UnimplementedPlacementResolverServiceServer) ResolveCloneAllocationPages(context.Context, *ResolveCloneAllocationPagesRequest) (*ResolveCloneAllocationPagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveCloneAllocationPages not implemented")
}
func (UnimplementedPlacementResolverServiceServer) mustEmbedUnimplementedPlacementResolverServiceServer() {
}
func (UnimplementedPlacementResolverServiceServer) testEmbeddedByValue() {}

// UnsafePlacementResolverServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlacementResolverServiceServer will
// result in compilation errors.
type UnsafePlacementResolverServiceServer interface {
	mustEmbedUnimplementedPlacementResolverServiceServer()
}

func RegisterPlacementResolverServiceServer(s grpc.ServiceRegistrar, srv PlacementResolverServiceServer) {
	// If the following call pancis, it indicates UnimplementedPlacementResolverServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlacementResolverService_ServiceDesc, srv)
}

func _PlacementResolverService_ResolveExtentPlacements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveExtentPlacementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlacementResolverServiceServer).ResolveExtentPlacements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlacementResolverService_ResolveExtentPlacements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlacementResolverServiceServer).ResolveExtentPlacements(ctx, req.(*ResolveExtentPlacementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlacementResolverService_ResolveAllocationPages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveAllocationPagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlacementResolverServiceServer).ResolveAllocationPages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlacementResolverService_ResolveAllocationPages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlacementResolverServiceServer).ResolveAllocationPages(ctx, req.(*ResolveAllocationPagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlacementResolverService_ResolveSnapshotAllocationPages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveSnapshotAllocationPagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlacementResolverServiceServer).ResolveSnapshotAllocationPages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlacementResolverService_ResolveSnapshotAllocationPages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlacementResolverServiceServer).ResolveSnapshotAllocationPages(ctx, req.(*ResolveSnapshotAllocationPagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlacementResolverService_ResolveCloneAllocationPages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveCloneAllocationPagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlacementResolverServiceServer).ResolveCloneAllocationPages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlacementResolverService_ResolveCloneAllocationPages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlacementResolverServiceServer).ResolveCloneAllocationPages(ctx, req.(*ResolveCloneAllocationPagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlacementResolverService_ServiceDesc is the grpc.ServiceDesc for PlacementResolverService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlacementResolverService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sbs.internalapi.v1.PlacementResolverService",
	HandlerType: (*PlacementResolverServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveExtentPlacements",
			Handler:    _PlacementResolverService_ResolveExtentPlacements_Handler,
		},
		{
			MethodName: "ResolveAllocationPages",
			Handler:    _PlacementResolverService_ResolveAllocationPages_Handler,
		},
		{
			MethodName: "ResolveSnapshotAllocationPages",
			Handler:    _PlacementResolverService_ResolveSnapshotAllocationPages_Handler,
		},
		{
			MethodName: "ResolveCloneAllocationPages",
			Handler:    _PlacementResolverService_ResolveCloneAllocationPages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sbs/internalapi/v1/placement_resolver.proto",
}
