// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: sbs/internalapi/v1/placement_apply.proto

package internalv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlacementApplyService_ApplyPlacementChanges_FullMethodName = "/sbs.internalapi.v1.PlacementApplyService/ApplyPlacementChanges"
)

// PlacementApplyServiceClient is the client API for PlacementApplyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PlacementApplyService is an internal-only authority surface for applying
// committed placement effects owned by sbs-service.
type PlacementApplyServiceClient interface {
	ApplyPlacementChanges(ctx context.Context, in *ApplyPlacementChangesRequest, opts ...grpc.CallOption) (*ApplyPlacementChangesResponse, error)
}

type placementApplyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlacementApplyServiceClient(cc grpc.ClientConnInterface) PlacementApplyServiceClient {
	return &placementApplyServiceClient{cc}
}

func (c *placementApplyServiceClient) ApplyPlacementChanges(ctx context.Context, in *ApplyPlacementChangesRequest, opts ...grpc.CallOption) (*ApplyPlacementChangesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyPlacementChangesResponse)
	err := c.cc.Invoke(ctx, PlacementApplyService_ApplyPlacementChanges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlacementApplyServiceServer is the server API for PlacementApplyService service.
// All implementations must embed UnimplementedPlacementApplyServiceServer
// for forward compatibility.
//
// PlacementApplyService is an internal-only authority surface for applying
// committed placement effects owned by sbs-service.
type PlacementApplyServiceServer interface {
	ApplyPlacementChanges(context.Context, *ApplyPlacementChangesRequest) (*ApplyPlacementChangesResponse, error)
	mustEmbedUnimplementedPlacementApplyServiceServer()
}

// UnimplementedPlacementApplyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlacementApplyServiceServer struct{}

func (UnimplementedPlacementApplyServiceServer) ApplyPlacementChanges(context.Context, *ApplyPlacementChangesRequest) (*ApplyPlacementChangesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyPlacementChanges not implemented")
}
func (UnimplementedPlacementApplyServiceServer) mustEmbedUnimplementedPlacementApplyServiceServer() {}
func (UnimplementedPlacementApplyServiceServer) testEmbeddedByValue()                               {}

// UnsafePlacementApplyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlacementApplyServiceServer will
// result in compilation errors.
type UnsafePlacementApplyServiceServer interface {
	mustEmbedUnimplementedPlacementApplyServiceServer()
}

func RegisterPlacementApplyServiceServer(s grpc.ServiceRegistrar, srv PlacementApplyServiceServer) {
	// If the following call pancis, it indicates UnimplementedPlacementApplyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlacementApplyService_ServiceDesc, srv)
}

func _PlacementApplyService_ApplyPlacementChanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyPlacementChangesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlacementApplyServiceServer).ApplyPlacementChanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlacementApplyService_ApplyPlacementChanges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlacementApplyServiceServer).ApplyPlacementChanges(ctx, req.(*ApplyPlacementChangesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlacementApplyService_ServiceDesc is the grpc.ServiceDesc for PlacementApplyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlacementApplyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sbs.internalapi.v1.PlacementApplyService",
	HandlerType: (*PlacementApplyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyPlacementChanges",
			Handler:    _PlacementApplyService_ApplyPlacementChanges_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sbs/internalapi/v1/placement_apply.proto",
}
