// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: sbs/internalapi/v1/write_session.proto

package internalv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WriteSessionService_GetVolumeState_FullMethodName                            = "/sbs.internalapi.v1.WriteSessionService/GetVolumeState"
	WriteSessionService_PutVolumeState_FullMethodName                            = "/sbs.internalapi.v1.WriteSessionService/PutVolumeState"
	WriteSessionService_GetIdempotencyRecord_FullMethodName                      = "/sbs.internalapi.v1.WriteSessionService/GetIdempotencyRecord"
	WriteSessionService_PutIdempotencyRecord_FullMethodName                      = "/sbs.internalapi.v1.WriteSessionService/PutIdempotencyRecord"
	WriteSessionService_GetMutationOperation_FullMethodName                      = "/sbs.internalapi.v1.WriteSessionService/GetMutationOperation"
	WriteSessionService_PutMutationOperation_FullMethodName                      = "/sbs.internalapi.v1.WriteSessionService/PutMutationOperation"
	WriteSessionService_PutWriteIntent_FullMethodName                            = "/sbs.internalapi.v1.WriteSessionService/PutWriteIntent"
	WriteSessionService_CommitWriteState_FullMethodName                          = "/sbs.internalapi.v1.WriteSessionService/CommitWriteState"
	WriteSessionService_CommitPageScopedWriteMetadata_FullMethodName             = "/sbs.internalapi.v1.WriteSessionService/CommitPageScopedWriteMetadata"
	WriteSessionService_CommitRangeLocalWriteState_FullMethodName                = "/sbs.internalapi.v1.WriteSessionService/CommitRangeLocalWriteState"
	WriteSessionService_CommitAppendOnlyWriteStateAndQueueEffects_FullMethodName = "/sbs.internalapi.v1.WriteSessionService/CommitAppendOnlyWriteStateAndQueueEffects"
	WriteSessionService_CommitCloneDeltaAllocationPages_FullMethodName           = "/sbs.internalapi.v1.WriteSessionService/CommitCloneDeltaAllocationPages"
)

// WriteSessionServiceClient is the client API for WriteSessionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WriteSessionService is an internal-only authority surface for committing the
// state/control-record half of a gateway write.
type WriteSessionServiceClient interface {
	GetVolumeState(ctx context.Context, in *GetVolumeStateRequest, opts ...grpc.CallOption) (*GetVolumeStateResponse, error)
	PutVolumeState(ctx context.Context, in *PutVolumeStateRequest, opts ...grpc.CallOption) (*PutVolumeStateResponse, error)
	GetIdempotencyRecord(ctx context.Context, in *GetIdempotencyRecordRequest, opts ...grpc.CallOption) (*GetIdempotencyRecordResponse, error)
	PutIdempotencyRecord(ctx context.Context, in *PutIdempotencyRecordRequest, opts ...grpc.CallOption) (*PutIdempotencyRecordResponse, error)
	GetMutationOperation(ctx context.Context, in *GetMutationOperationRequest, opts ...grpc.CallOption) (*GetMutationOperationResponse, error)
	PutMutationOperation(ctx context.Context, in *PutMutationOperationRequest, opts ...grpc.CallOption) (*PutMutationOperationResponse, error)
	PutWriteIntent(ctx context.Context, in *PutWriteIntentRequest, opts ...grpc.CallOption) (*PutWriteIntentResponse, error)
	CommitWriteState(ctx context.Context, in *CommitWriteStateRequest, opts ...grpc.CallOption) (*CommitWriteStateResponse, error)
	CommitPageScopedWriteMetadata(ctx context.Context, in *CommitPageScopedWriteMetadataRequest, opts ...grpc.CallOption) (*CommitPageScopedWriteMetadataResponse, error)
	CommitRangeLocalWriteState(ctx context.Context, in *CommitRangeLocalWriteStateRequest, opts ...grpc.CallOption) (*CommitRangeLocalWriteStateResponse, error)
	CommitAppendOnlyWriteStateAndQueueEffects(ctx context.Context, in *CommitAppendOnlyWriteStateAndQueueEffectsRequest, opts ...grpc.CallOption) (*CommitAppendOnlyWriteStateAndQueueEffectsResponse, error)
	CommitCloneDeltaAllocationPages(ctx context.Context, in *CommitCloneDeltaAllocationPagesRequest, opts ...grpc.CallOption) (*CommitCloneDeltaAllocationPagesResponse, error)
}

type writeSessionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWriteSessionServiceClient(cc grpc.ClientConnInterface) WriteSessionServiceClient {
	return &writeSessionServiceClient{cc}
}

func (c *writeSessionServiceClient) GetVolumeState(ctx context.Context, in *GetVolumeStateRequest, opts ...grpc.CallOption) (*GetVolumeStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVolumeStateResponse)
	err := c.cc.Invoke(ctx, WriteSessionService_GetVolumeState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *writeSessionServiceClient) PutVolumeState(ctx context.Context, in *PutVolumeStateRequest, opts ...grpc.CallOption) (*PutVolumeStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutVolumeStateResponse)
	err := c.cc.Invoke(ctx, WriteSessionService_PutVolumeState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *writeSessionServiceClient) GetIdempotencyRecord(ctx context.Context, in *GetIdempotencyRecordRequest, opts ...grpc.CallOption) (*GetIdempotencyRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIdempotencyRecordResponse)
	err := c.cc.Invoke(ctx, WriteSessionService_GetIdempotencyRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *writeSessionServiceClient) PutIdempotencyRecord(ctx context.Context, in *PutIdempotencyRecordRequest, opts ...grpc.CallOption) (*PutIdempotencyRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutIdempotencyRecordResponse)
	err := c.cc.Invoke(ctx, WriteSessionService_PutIdempotencyRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *writeSessionServiceClient) GetMutationOperation(ctx context.Context, in *GetMutationOperationRequest, opts ...grpc.CallOption) (*GetMutationOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMutationOperationResponse)
	err := c.cc.Invoke(ctx, WriteSessionService_GetMutationOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *writeSessionServiceClient) PutMutationOperation(ctx context.Context, in *PutMutationOperationRequest, opts ...grpc.CallOption) (*PutMutationOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutMutationOperationResponse)
	err := c.cc.Invoke(ctx, WriteSessionService_PutMutationOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *writeSessionServiceClient) PutWriteIntent(ctx context.Context, in *PutWriteIntentRequest, opts ...grpc.CallOption) (*PutWriteIntentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutWriteIntentResponse)
	err := c.cc.Invoke(ctx, WriteSessionService_PutWriteIntent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *writeSessionServiceClient) CommitWriteState(ctx context.Context, in *CommitWriteStateRequest, opts ...grpc.CallOption) (*CommitWriteStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitWriteStateResponse)
	err := c.cc.Invoke(ctx, WriteSessionService_CommitWriteState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *writeSessionServiceClient) CommitPageScopedWriteMetadata(ctx context.Context, in *CommitPageScopedWriteMetadataRequest, opts ...grpc.CallOption) (*CommitPageScopedWriteMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitPageScopedWriteMetadataResponse)
	err := c.cc.Invoke(ctx, WriteSessionService_CommitPageScopedWriteMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *writeSessionServiceClient) CommitRangeLocalWriteState(ctx context.Context, in *CommitRangeLocalWriteStateRequest, opts ...grpc.CallOption) (*CommitRangeLocalWriteStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitRangeLocalWriteStateResponse)
	err := c.cc.Invoke(ctx, WriteSessionService_CommitRangeLocalWriteState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *writeSessionServiceClient) CommitAppendOnlyWriteStateAndQueueEffects(ctx context.Context, in *CommitAppendOnlyWriteStateAndQueueEffectsRequest, opts ...grpc.CallOption) (*CommitAppendOnlyWriteStateAndQueueEffectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitAppendOnlyWriteStateAndQueueEffectsResponse)
	err := c.cc.Invoke(ctx, WriteSessionService_CommitAppendOnlyWriteStateAndQueueEffects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *writeSessionServiceClient) CommitCloneDeltaAllocationPages(ctx context.Context, in *CommitCloneDeltaAllocationPagesRequest, opts ...grpc.CallOption) (*CommitCloneDeltaAllocationPagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitCloneDeltaAllocationPagesResponse)
	err := c.cc.Invoke(ctx, WriteSessionService_CommitCloneDeltaAllocationPages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WriteSessionServiceServer is the server API for WriteSessionService service.
// All implementations must embed UnimplementedWriteSessionServiceServer
// for forward compatibility.
//
// WriteSessionService is an internal-only authority surface for committing the
// state/control-record half of a gateway write.
type WriteSessionServiceServer interface {
	GetVolumeState(context.Context, *GetVolumeStateRequest) (*GetVolumeStateResponse, error)
	PutVolumeState(context.Context, *PutVolumeStateRequest) (*PutVolumeStateResponse, error)
	GetIdempotencyRecord(context.Context, *GetIdempotencyRecordRequest) (*GetIdempotencyRecordResponse, error)
	PutIdempotencyRecord(context.Context, *PutIdempotencyRecordRequest) (*PutIdempotencyRecordResponse, error)
	GetMutationOperation(context.Context, *GetMutationOperationRequest) (*GetMutationOperationResponse, error)
	PutMutationOperation(context.Context, *PutMutationOperationRequest) (*PutMutationOperationResponse, error)
	PutWriteIntent(context.Context, *PutWriteIntentRequest) (*PutWriteIntentResponse, error)
	CommitWriteState(context.Context, *CommitWriteStateRequest) (*CommitWriteStateResponse, error)
	CommitPageScopedWriteMetadata(context.Context, *CommitPageScopedWriteMetadataRequest) (*CommitPageScopedWriteMetadataResponse, error)
	CommitRangeLocalWriteState(context.Context, *CommitRangeLocalWriteStateRequest) (*CommitRangeLocalWriteStateResponse, error)
	CommitAppendOnlyWriteStateAndQueueEffects(context.Context, *CommitAppendOnlyWriteStateAndQueueEffectsRequest) (*CommitAppendOnlyWriteStateAndQueueEffectsResponse, error)
	CommitCloneDeltaAllocationPages(context.Context, *CommitCloneDeltaAllocationPagesRequest) (*CommitCloneDeltaAllocationPagesResponse, error)
	mustEmbedUnimplementedWriteSessionServiceServer()
}

// UnimplementedWriteSessionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWriteSessionServiceServer struct{}

func (UnimplementedWriteSessionServiceServer) GetVolumeState(context.Context, *GetVolumeStateRequest) (*GetVolumeStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVolumeState not implemented")
}
func (UnimplementedWriteSessionServiceServer) PutVolumeState(context.Context, *PutVolumeStateRequest) (*PutVolumeStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutVolumeState not implemented")
}
func (UnimplementedWriteSessionServiceServer) GetIdempotencyRecord(context.Context, *GetIdempotencyRecordRequest) (*GetIdempotencyRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIdempotencyRecord not implemented")
}
func (UnimplementedWriteSessionServiceServer) PutIdempotencyRecord(context.Context, *PutIdempotencyRecordRequest) (*PutIdempotencyRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutIdempotencyRecord not implemented")
}
func (UnimplementedWriteSessionServiceServer) GetMutationOperation(context.Context, *GetMutationOperationRequest) (*GetMutationOperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMutationOperation not implemented")
}
func (UnimplementedWriteSessionServiceServer) PutMutationOperation(context.Context, *PutMutationOperationRequest) (*PutMutationOperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutMutationOperation not implemented")
}
func (UnimplementedWriteSessionServiceServer) PutWriteIntent(context.Context, *PutWriteIntentRequest) (*PutWriteIntentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutWriteIntent not implemented")
}
func (UnimplementedWriteSessionServiceServer) CommitWriteState(context.Context, *CommitWriteStateRequest) (*CommitWriteStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitWriteState not implemented")
}
func (UnimplementedWriteSessionServiceServer) CommitPageScopedWriteMetadata(context.Context, *CommitPageScopedWriteMetadataRequest) (*CommitPageScopedWriteMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitPageScopedWriteMetadata not implemented")
}
func (UnimplementedWriteSessionServiceServer) CommitRangeLocalWriteState(context.Context, *CommitRangeLocalWriteStateRequest) (*CommitRangeLocalWriteStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitRangeLocalWriteState not implemented")
}
func (UnimplementedWriteSessionServiceServer) CommitAppendOnlyWriteStateAndQueueEffects(context.Context, *CommitAppendOnlyWriteStateAndQueueEffectsRequest) (*CommitAppendOnlyWriteStateAndQueueEffectsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitAppendOnlyWriteStateAndQueueEffects not implemented")
}
func (UnimplementedWriteSessionServiceServer) CommitCloneDeltaAllocationPages(context.Context, *CommitCloneDeltaAllocationPagesRequest) (*CommitCloneDeltaAllocationPagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitCloneDeltaAllocationPages not implemented")
}
func (UnimplementedWriteSessionServiceServer) mustEmbedUnimplementedWriteSessionServiceServer() {}
func (UnimplementedWriteSessionServiceServer) testEmbeddedByValue()                             {}

// UnsafeWriteSessionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WriteSessionServiceServer will
// result in compilation errors.
type UnsafeWriteSessionServiceServer interface {
	mustEmbedUnimplementedWriteSessionServiceServer()
}

func RegisterWriteSessionServiceServer(s grpc.ServiceRegistrar, srv WriteSessionServiceServer) {
	// If the following call pancis, it indicates UnimplementedWriteSessionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WriteSessionService_ServiceDesc, srv)
}

func _WriteSessionService_GetVolumeState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVolumeStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WriteSessionServiceServer).GetVolumeState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WriteSessionService_GetVolumeState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WriteSessionServiceServer).GetVolumeState(ctx, req.(*GetVolumeStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WriteSessionService_PutVolumeState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutVolumeStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WriteSessionServiceServer).PutVolumeState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WriteSessionService_PutVolumeState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WriteSessionServiceServer).PutVolumeState(ctx, req.(*PutVolumeStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WriteSessionService_GetIdempotencyRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIdempotencyRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WriteSessionServiceServer).GetIdempotencyRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WriteSessionService_GetIdempotencyRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WriteSessionServiceServer).GetIdempotencyRecord(ctx, req.(*GetIdempotencyRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WriteSessionService_PutIdempotencyRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutIdempotencyRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WriteSessionServiceServer).PutIdempotencyRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WriteSessionService_PutIdempotencyRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WriteSessionServiceServer).PutIdempotencyRecord(ctx, req.(*PutIdempotencyRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WriteSessionService_GetMutationOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMutationOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WriteSessionServiceServer).GetMutationOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WriteSessionService_GetMutationOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WriteSessionServiceServer).GetMutationOperation(ctx, req.(*GetMutationOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WriteSessionService_PutMutationOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutMutationOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WriteSessionServiceServer).PutMutationOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WriteSessionService_PutMutationOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WriteSessionServiceServer).PutMutationOperation(ctx, req.(*PutMutationOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WriteSessionService_PutWriteIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutWriteIntentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WriteSessionServiceServer).PutWriteIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WriteSessionService_PutWriteIntent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WriteSessionServiceServer).PutWriteIntent(ctx, req.(*PutWriteIntentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WriteSessionService_CommitWriteState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitWriteStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WriteSessionServiceServer).CommitWriteState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WriteSessionService_CommitWriteState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WriteSessionServiceServer).CommitWriteState(ctx, req.(*CommitWriteStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WriteSessionService_CommitPageScopedWriteMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitPageScopedWriteMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WriteSessionServiceServer).CommitPageScopedWriteMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WriteSessionService_CommitPageScopedWriteMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WriteSessionServiceServer).CommitPageScopedWriteMetadata(ctx, req.(*CommitPageScopedWriteMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WriteSessionService_CommitRangeLocalWriteState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRangeLocalWriteStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WriteSessionServiceServer).CommitRangeLocalWriteState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WriteSessionService_CommitRangeLocalWriteState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WriteSessionServiceServer).CommitRangeLocalWriteState(ctx, req.(*CommitRangeLocalWriteStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WriteSessionService_CommitAppendOnlyWriteStateAndQueueEffects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitAppendOnlyWriteStateAndQueueEffectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WriteSessionServiceServer).CommitAppendOnlyWriteStateAndQueueEffects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WriteSessionService_CommitAppendOnlyWriteStateAndQueueEffects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WriteSessionServiceServer).CommitAppendOnlyWriteStateAndQueueEffects(ctx, req.(*CommitAppendOnlyWriteStateAndQueueEffectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WriteSessionService_CommitCloneDeltaAllocationPages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitCloneDeltaAllocationPagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WriteSessionServiceServer).CommitCloneDeltaAllocationPages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WriteSessionService_CommitCloneDeltaAllocationPages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WriteSessionServiceServer).CommitCloneDeltaAllocationPages(ctx, req.(*CommitCloneDeltaAllocationPagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WriteSessionService_ServiceDesc is the grpc.ServiceDesc for WriteSessionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WriteSessionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sbs.internalapi.v1.WriteSessionService",
	HandlerType: (*WriteSessionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVolumeState",
			Handler:    _WriteSessionService_GetVolumeState_Handler,
		},
		{
			MethodName: "PutVolumeState",
			Handler:    _WriteSessionService_PutVolumeState_Handler,
		},
		{
			MethodName: "GetIdempotencyRecord",
			Handler:    _WriteSessionService_GetIdempotencyRecord_Handler,
		},
		{
			MethodName: "PutIdempotencyRecord",
			Handler:    _WriteSessionService_PutIdempotencyRecord_Handler,
		},
		{
			MethodName: "GetMutationOperation",
			Handler:    _WriteSessionService_GetMutationOperation_Handler,
		},
		{
			MethodName: "PutMutationOperation",
			Handler:    _WriteSessionService_PutMutationOperation_Handler,
		},
		{
			MethodName: "PutWriteIntent",
			Handler:    _WriteSessionService_PutWriteIntent_Handler,
		},
		{
			MethodName: "CommitWriteState",
			Handler:    _WriteSessionService_CommitWriteState_Handler,
		},
		{
			MethodName: "CommitPageScopedWriteMetadata",
			Handler:    _WriteSessionService_CommitPageScopedWriteMetadata_Handler,
		},
		{
			MethodName: "CommitRangeLocalWriteState",
			Handler:    _WriteSessionService_CommitRangeLocalWriteState_Handler,
		},
		{
			MethodName: "CommitAppendOnlyWriteStateAndQueueEffects",
			Handler:    _WriteSessionService_CommitAppendOnlyWriteStateAndQueueEffects_Handler,
		},
		{
			MethodName: "CommitCloneDeltaAllocationPages",
			Handler:    _WriteSessionService_CommitCloneDeltaAllocationPages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sbs/internalapi/v1/write_session.proto",
}
