apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: namrbd-snapshot
  labels:
    app.kubernetes.io/name: namrbd-csi
driver: __DRIVER_NAME__
deletionPolicy: Delete
parameters: {}
